### ISSUE TITLE
How to use a mock with a fixture?

### ISSUE THREAD

**Issue by U007D** [mindsbackyard/galvanic-mock#3]
When in #2 when I set my fixture to return a trait, I got a compiler error because the trait's size was not known at compile time.  I tried `Box`ing (`-> Box<Foo>`) but that did not work either.

Can you provide or point me to an example where a mock of a trait is returned by a fixture?

I have looked at [this example provided in `galvanic-test`](https://github.com/mindsbackyard/galvanic-test/blob/master/tests/galvanic_mock_integration.rs), but when I try to duplicate it, I get an error indicating that `mock::TestMock` is not defined.  (I also tried `mock::InfoMock`, in case the return type is being autogenerated from the fixture name (`info_mock()`), but no luck there, either).

I ran `galvanic-test`'s integration tests to see how the above mentioned example could work, but it appears that integration test is disabled somehow--here is the relevant excerpt from the `cargo test` output:

```
     Running target/debug/deps/galvanic_mock_integration-a063f8dd34fb6889

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Thoughts/help/ideas welcome!  Many thanks.

**Comment by mindsbackyard** [comment]
Yes, you are right by default the integration is disabled as galvanic-mock currently supports only nightly.
You need to enable the `galvanic_mock_integraion` feature (either via command line or in your cargo.toml). You can see the difference if you run `cargo test --features galvanic_mock_integration` in the `galvanic-test` crate. It should output:
```
     Running target/debug/deps/galvanic_mock_integration-eba0e009898b208e

running 1 test

test inject_mock::mod_with_mocks::with_mocks::inject_mock ... ok
```

**Comment by U007D** [comment]
Excerpt from Cargo.toml:
```toml
[dependencies.galvanic-assert]
version = "*"

[dependencies.galvanic-mock]
features = ["galvanic_assert_integration"]
version = "*"

[dependencies.galvanic-test]
features = ["galvanic_mock_integration"]
version = "*"
```
Test:
```
use super::*;
use galvanic_test::*;
use galvanic_assert::matchers::*;
use galvanic_mock::{mockable, use_mocks};
use galvanic_mock::*; //used in galvanic_mock_integration.rs example

#[allow(redundant_closure, trivial_casts, unused_qualifications)] //does nothing; TODO: open issues
test_suite! {
    name app_tests;
    use super::*;

    fixture info_mock() -> mock::TestMock {
        setup(&mut self) {
            // given
            let arch_width = 42_usize;
            let mock = new_mock!(Info as InfoMock);

            given! {
                bind arch_width: usize = arch_width;
                <mock as Info>::width any_value() then_return bound.arch_width times 1;
            }
            InfoMock
        }
    }

    test yields_expected_word_width(info_mock) {
        let expected_result = format!("Hello, {}-bit world!", arch_width);
        let subject = App::new(info_mock.into_val());

        // when
        let result = subject.run();

        // then
        // the app returned the expected word width
        assert_eq!(result.unwrap(), expected_result);
    }
}
```
Yields:
```
error: custom attribute panicked
  --> src/lib/unit_tests/mod.rs:8:1
   |
8  | / test_suite! {
9  | |     name app_tests;
10 | |     use super::*;
11 | |
...  |
36 | |     }
37 | | }
   | |_^
   |
   = help: message: Expecting a new_mock defintion of the form: new_mock!(paths::to::Traits, ... #[optional_attributes]...);
            Got: new_mock ! ( Info as InfoMock ) ; given ! { bind arch_width : usize = arch_width ; < mock as Info > :: width any_value ( ) then_return bound . arch_width times 1 ; } InfoMock } } test yields_expected_word_width ( info_mock ) { let expected_result = format ! ( "Hello, {}-bit world!" , arch_width ) ; let subject = App :: new ( info_mock . into_val ( ) ) ; let result = subject . run ( ) ; assert_eq ! ( result . unwrap ( ) , expected_result ) ; } ) ; }
   = note: this error originates in a macro outside of the current crate
```

**Comment by mindsbackyard** [comment]
It should be `new_mock!(Info for InfoMock);`. The error message seems not to be outdated here.

**Comment by U007D** [comment]
Oh, that's my mistake.  Sorry.

After making the (proper) change, I'm now getting:
```
error[E0425]: cannot find value `InfoMock` in this scope
  --> src/lib/unit_tests/mod.rs:8:1
   |
8  | / test_suite! {
9  | |     name app_tests;
10 | |     use super::*;
11 | |
...  |
36 | |     }
37 | | }
   | |_^ not found in this scope
   |
   = note: this error originates in a macro outside of the current crate

error[E0425]: cannot find value `arch_width` in this scope
  --> src/lib/unit_tests/mod.rs:8:1
   |
8  | / test_suite! {
9  | |     name app_tests;
10 | |     use super::*;
11 | |
...  |
36 | |     }
37 | | }
   | |_^ not found in this scope
   |
   = note: this error originates in a macro outside of the current crate
```

**Comment by mindsbackyard** [comment]
Here you have
```rust
         <mock as Info>::width any_value() then_return bound.arch_width times 1;
            }
            InfoMock
        }
```
but `mock::InfoMock` is a type not a value. You'd need to return the `mock` variable here. (I'd advise againt naming the variable mock as it shadows the module.)

**Comment by U007D** [comment]
ok, `fixture info_mock() -> ???` looks similar to a function signature,  I'm assuming the `???` should be a type and not a value, correct? (patterning after function declarations: e.g. `fn foo() -> i8`)

If correct, I'd need to know the type of a mock generated by `new_mock!`, if mock::InfoMock isn't the correct type.

Here's the latest, with your suggestions re: shadowing taken into account:
```
test_suite! {
    name app_tests;
    use super::*;

    fixture info_mock() -> mock::InfoMock {
        setup(&mut self) {
            // given
            let arch_width = 42_usize;
            let my_mock = new_mock!(Info for InfoMock);

            given! {
                bind arch_width: usize = arch_width;
                <mock as Info>::width any_value() then_return bound.arch_width times 1;
            }
            my_mock
        }
    }

    test yields_expected_word_width(info_mock) {
        let expected_result = format!("Hello, {}-bit world!", arch_width);
        let subject = App::new(info_mock.into_val());

        // when
        let result = subject.run();

        // then
        // the app returned the expected word width
        assert_eq!(result.unwrap(), expected_result);
    }
}
```

This gives:
```
error[E0423]: expected value, found module `mock`
  --> src/lib/unit_tests/mod.rs:8:1
   |
8  | / test_suite! {
9  | |     name app_tests;
10 | |     use super::*;
11 | |
...  |
36 | |     }
37 | | }
   | |_^ did you mean `mock::add_given_behaviour(...)`?
   |
   = note: this error originates in a macro outside of the current crate

error[E0425]: cannot find value `arch_width` in this scope
  --> src/lib/unit_tests/mod.rs:8:1
   |
8  | / test_suite! {
9  | |     name app_tests;
10 | |     use super::*;
11 | |
...  |
36 | |     }
37 | | }
   | |_^ not found in this scope
   |
   = note: this error originates in a macro outside of the current crate

error: aborting due to 2 previous errors
```
So, 1) my type/return type still seems to be wrong (I get the same error whether or not `InfoMock` is prefixed with `mock::`, and 2) the `bound` type does not appear that it is being picked up.

**Comment by mindsbackyard** [comment]
You forgot to rename the mock variable usage inside of the given
definition. As for the arch_width issue I'll have to try myself. Maybe try
to rename it in one place s.t. the error message is less ambiguous?

**Comment by U007D** [comment]
Oh, so sorry for the renaming issue--I did indeed miss it and it seems to be fixed now, thank you.

Re: the missing binding, I named the `bind` to foo, and it's still complaining about `cannot find value 'arch_width'`.  I also tried using `arch_width` as a parameter to `info_mock` instead of a binding within `info_mock`.  I got the same failure, but with a hint to try `self.info_mock`.  I did, but the error persisted (without the hint this time).

**Comment by U007D** [comment]
I found the binding problem too.  Again in my code--I've got it now.  :)

Thank you so much for helping me get my head wrapped around writing a fixtured mock in galvanic!

**Comment by mindsbackyard** [comment]
What was the problem?

**Comment by U007D** [comment]
My `format!()` line in the `test` itself was attempting to reference the `let arch_width =` binding defined in the `given!` clause.  I wasn't actually trying to access it, it was just a leftover from when I had tried defining it in different places to get it to work.

Renaming `arch_width` in the `fixture` and in the `setup()` as per your suggestion revealed this.

Thanks again!

**Comment by U007D** [comment]
For anyone else who may be trying to do this:  Here's the working code, using a value passed into the fixture as a parameter:

```
test_suite! {
    name app_tests;
    use super::*;

    fixture info_mock(arch_width: usize) -> mock::InfoMock {
        setup(&mut self) {
            let mock = new_mock!(Info for InfoMock);

            given! {
                bind arch_width: usize = *self.arch_width;
                <mock as Info>::width any_value() then_return bound.arch_width times 1;
            }
            mock
        }
    }

    test yields_expected_word_width(info_mock(42)) {
        // given
        let expected_result = format!("Hello, {}-bit world!", info_mock.params.arch_width);
        let subject = App::new(info_mock.into_val()).unwrap();

        // when
        let result = subject.run();

        // then
        // the app returned the expected word width
        assert_eq!(result.unwrap(), expected_result);
    }
}
```
Note, the `bind` in the `given!` macro required a deref of a `&'param usize` to use as a `usize`; I didn't see this documented in `galvanic-test` or `galvanic-mock`, so know that this is a possible source of `mismached type` compiler errors.
